name: Deno CD

on:
  release:
    types: [released]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Deno Official
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Compile for Linux x86_64
        run: deno compile --allow-read --allow-write --allow-run --allow-net --reload --target x86_64-unknown-linux-gnu --output fern_linux-x86_64 fern.ts

      - name: Compile for Windows x86_64
        run: deno compile --allow-read --allow-write --allow-run --allow-net --reload --target x86_64-pc-windows-msvc --output fern_windows-x86_64 fern.ts

      - name: Compile for Darwin x86_64
        run: deno compile --allow-read --allow-write --allow-run --allow-net --reload --target x86_64-apple-darwin --output fern_darwin-x86_64 fern.ts

      - name: Compile for Darwin aarch64
        run: deno compile --allow-read --allow-write --allow-run --allow-net --reload --target aarch64-apple-darwin --output fern_darwin-aarch64 fern.ts

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fern
          path: |
            fern_linux-x86_64
            fern_windows-x86_64
            fern_darwin-x86_64
            fern_darwin-aarch64
